CC = gcc
ALL = dp problem1 problem2 problem3-1 problem3-2

all: $(ALL)
dp: dp.c
	$(CC) -lpthread -std=gnu99 dp.c -o dp
problem1: problem1.c
	$(CC) -lpthread  problem1.c -o problem1

problem2: problem2.c
	$(CC) -lpthread problem2.c -o problem2

problem3-1: problem3-1.c
	$(CC) -lpthread problem3-1.c -o problem3-1

problem3-2: problem3-2.c
	$(CC) -lpthread problem3-2.c -o problem3-2